spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xuexi007/java0114-configserver
          username: xuexi007
          password: Offcn123
          search-paths: offcn/config-repo
server:
  port: 7002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka
