#服务器启动端口号
server:
  port: 10087
#应用的名称
spring:
  application:
    name: EurekaServer
#EurekaServer配置

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka  #把注册地址指向注册中心1

