spring:
  application:
    name: api-gateway
server:
  port: 80
zuul:
  routes:
    demo1:
      path: /demo1/**
      url: http://localhost:8008/
    demo3:
      path: /demo3/**
      service-id: USERPROVIDER
  retryable: true
ribbon:
  ConnectionTimeOut: 1000
  ReadTimeout: 1000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 5
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka

